### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Kaika21** [RedLime/SpeedRunIGT#106]
The game crashes when i try changing the category in 1.20.4

**Comment by Libreh** [comment]
I can confirm, here's the crash log:
```
[Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1352) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.StackOverflowError
	at java.util.ArrayList.forEach(ArrayList.java:1506) ~[?:?]
	at com.redlimerl.speedrunigt.gui.screen.SpeedRunCategoryScreen$CategorySelectionListWidget$CategoryEntry.lambda$new$1(SpeedRunCategoryScreen.java:100) ~[SpeedRunIGT-13.6+1.20.4.jar:?]
	at net.minecraft.class_4286.method_25306(class_4286.java:112) ~[client-intermediary.jar:?]
	at com.redlimerl.speedrunigt.gui.screen.SpeedRunCategoryScreen$CategorySelectionListWidget$CategoryEntry.lambda$new$0(SpeedRunCategoryScreen.java:101) ~[SpeedRunIGT-13.6+1.20.4.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.redlimerl.speedrunigt.gui.screen.SpeedRunCategoryScreen$CategorySelectionListWidget$CategoryEntry.lambda$new$1(SpeedRunCategoryScreen.java:100) ~[SpeedRunIGT-13.6+1.20.4.jar:?]
	at net.minecraft.class_4286.method_25306(class_4286.java:112) ~[client-intermediary.jar:?]
	at
```
