### ISSUE TITLE
Game Crashes (1.16.1)

### ISSUE THREAD

**Issue by YellowBiskit** [RedLime/SpeedRunIGT#26]
I was trying to use the mod on 1.16.1 fabric (using the 1.16.1 jar ofc, and most recent version of mod) and the game crashes instantly when i click play. I'm using the most recent version of fabric (0.12.12) and this is the only mod I'm using.

the crashlog is below.

[22:39:44] [main/INFO]: Loading Minecraft 1.16.1 with Fabric Loader 0.12.12
[22:39:44] [main/INFO]: Loading 7 mods:
	- fabric-api-base 0.1.3+12a8474c02 via speedrunigt
	- fabric-key-binding-api-v1 1.0.1+f404f3be02 via speedrunigt
	- fabric-resource-loader-v0 0.2.6+f41e209802 via speedrunigt
	- fabricloader 0.12.12
	- java 8
	- minecraft 1.16.1
	- speedrunigt 4.19+1.16.1
[22:39:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/vm840/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[22:39:45] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config fabric-key-binding-api-v1.mixins.json for mod fabric-key-binding-api-v1
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.12.12.jar:?]
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config fabric-key-binding-api-v1.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-loader-0.12.12.jar:?]
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'fabric-key-binding-api-v1.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-loader-0.12.12.jar:?]
	... 3 more

**Comment by RedLime** [comment]
it seems fabric bug, did you tried again after reinstall fabric loader and speedrunigt?

**Comment by YellowBiskit** [comment]
yes, I have.

**Comment by RedLime** [comment]
please try again with 5.19
